// Code generated by protoc-gen-go. DO NOT EDIT.
// This is a simplified version for development purposes.

package productv1

import (
	"time"

	"google.golang.org/protobuf/types/known/timestamppb"
)

// Money represents a monetary value with precise arithmetic.
type Money struct {
	Numerator   int64 `protobuf:"varint,1,opt,name=numerator,proto3" json:"numerator,omitempty"`
	Denominator int64 `protobuf:"varint,2,opt,name=denominator,proto3" json:"denominator,omitempty"`
}

func (m *Money) GetNumerator() int64 {
	if m != nil {
		return m.Numerator
	}
	return 0
}

func (m *Money) GetDenominator() int64 {
	if m != nil {
		return m.Denominator
	}
	return 0
}

// Discount represents a percentage-based discount.
type Discount struct {
	Percentage int64                  `protobuf:"varint,1,opt,name=percentage,proto3" json:"percentage,omitempty"`
	StartDate  *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
}

func (d *Discount) GetPercentage() int64 {
	if d != nil {
		return d.Percentage
	}
	return 0
}

func (d *Discount) GetStartDate() *timestamppb.Timestamp {
	if d != nil {
		return d.StartDate
	}
	return nil
}

func (d *Discount) GetEndDate() *timestamppb.Timestamp {
	if d != nil {
		return d.EndDate
	}
	return nil
}

// Product represents a product in the catalog.
type Product struct {
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Category       string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	BasePrice      *Money                 `protobuf:"bytes,5,opt,name=base_price,json=basePrice,proto3" json:"base_price,omitempty"`
	EffectivePrice *Money                 `protobuf:"bytes,6,opt,name=effective_price,json=effectivePrice,proto3" json:"effective_price,omitempty"`
	Discount       *Discount              `protobuf:"bytes,7,opt,name=discount,proto3" json:"discount,omitempty"`
	Status         string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (p *Product) GetId() string {
	if p != nil {
		return p.Id
	}
	return ""
}

func (p *Product) GetName() string {
	if p != nil {
		return p.Name
	}
	return ""
}

func (p *Product) GetDescription() string {
	if p != nil {
		return p.Description
	}
	return ""
}

func (p *Product) GetCategory() string {
	if p != nil {
		return p.Category
	}
	return ""
}

func (p *Product) GetBasePrice() *Money {
	if p != nil {
		return p.BasePrice
	}
	return nil
}

func (p *Product) GetEffectivePrice() *Money {
	if p != nil {
		return p.EffectivePrice
	}
	return nil
}

func (p *Product) GetDiscount() *Discount {
	if p != nil {
		return p.Discount
	}
	return nil
}

func (p *Product) GetStatus() string {
	if p != nil {
		return p.Status
	}
	return ""
}

func (p *Product) GetCreatedAt() *timestamppb.Timestamp {
	if p != nil {
		return p.CreatedAt
	}
	return nil
}

func (p *Product) GetUpdatedAt() *timestamppb.Timestamp {
	if p != nil {
		return p.UpdatedAt
	}
	return nil
}

// ProductListItem represents a product in a list response.
type ProductListItem struct {
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Category        string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	BasePrice       *Money                 `protobuf:"bytes,5,opt,name=base_price,json=basePrice,proto3" json:"base_price,omitempty"`
	EffectivePrice  *Money                 `protobuf:"bytes,6,opt,name=effective_price,json=effectivePrice,proto3" json:"effective_price,omitempty"`
	DiscountPercent *int64                 `protobuf:"varint,7,opt,name=discount_percent,json=discountPercent,proto3,oneof" json:"discount_percent,omitempty"`
	Status          string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (p *ProductListItem) GetId() string {
	if p != nil {
		return p.Id
	}
	return ""
}

func (p *ProductListItem) GetName() string {
	if p != nil {
		return p.Name
	}
	return ""
}

func (p *ProductListItem) GetDescription() string {
	if p != nil {
		return p.Description
	}
	return ""
}

func (p *ProductListItem) GetCategory() string {
	if p != nil {
		return p.Category
	}
	return ""
}

func (p *ProductListItem) GetBasePrice() *Money {
	if p != nil {
		return p.BasePrice
	}
	return nil
}

func (p *ProductListItem) GetEffectivePrice() *Money {
	if p != nil {
		return p.EffectivePrice
	}
	return nil
}

func (p *ProductListItem) GetDiscountPercent() int64 {
	if p != nil && p.DiscountPercent != nil {
		return *p.DiscountPercent
	}
	return 0
}

func (p *ProductListItem) GetStatus() string {
	if p != nil {
		return p.Status
	}
	return ""
}

func (p *ProductListItem) GetCreatedAt() *timestamppb.Timestamp {
	if p != nil {
		return p.CreatedAt
	}
	return nil
}

// CreateProductRequest is the request to create a new product.
type CreateProductRequest struct {
	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Category    string `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	BasePrice   *Money `protobuf:"bytes,4,opt,name=base_price,json=basePrice,proto3" json:"base_price,omitempty"`
}

func (r *CreateProductRequest) GetName() string {
	if r != nil {
		return r.Name
	}
	return ""
}

func (r *CreateProductRequest) GetDescription() string {
	if r != nil {
		return r.Description
	}
	return ""
}

func (r *CreateProductRequest) GetCategory() string {
	if r != nil {
		return r.Category
	}
	return ""
}

func (r *CreateProductRequest) GetBasePrice() *Money {
	if r != nil {
		return r.BasePrice
	}
	return nil
}

// CreateProductReply is the response after creating a product.
type CreateProductReply struct {
	ProductId string `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
}

func (r *CreateProductReply) GetProductId() string {
	if r != nil {
		return r.ProductId
	}
	return ""
}

// UpdateProductRequest is the request to update a product.
type UpdateProductRequest struct {
	ProductId   string `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Category    string `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
}

func (r *UpdateProductRequest) GetProductId() string {
	if r != nil {
		return r.ProductId
	}
	return ""
}

func (r *UpdateProductRequest) GetName() string {
	if r != nil {
		return r.Name
	}
	return ""
}

func (r *UpdateProductRequest) GetDescription() string {
	if r != nil {
		return r.Description
	}
	return ""
}

func (r *UpdateProductRequest) GetCategory() string {
	if r != nil {
		return r.Category
	}
	return ""
}

// UpdateProductReply is the response after updating a product.
type UpdateProductReply struct{}

// ActivateProductRequest is the request to activate a product.
type ActivateProductRequest struct {
	ProductId string `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
}

func (r *ActivateProductRequest) GetProductId() string {
	if r != nil {
		return r.ProductId
	}
	return ""
}

// ActivateProductReply is the response after activating a product.
type ActivateProductReply struct{}

// DeactivateProductRequest is the request to deactivate a product.
type DeactivateProductRequest struct {
	ProductId string `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
}

func (r *DeactivateProductRequest) GetProductId() string {
	if r != nil {
		return r.ProductId
	}
	return ""
}

// DeactivateProductReply is the response after deactivating a product.
type DeactivateProductReply struct{}

// ArchiveProductRequest is the request to archive a product.
type ArchiveProductRequest struct {
	ProductId string `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
}

func (r *ArchiveProductRequest) GetProductId() string {
	if r != nil {
		return r.ProductId
	}
	return ""
}

// ArchiveProductReply is the response after archiving a product.
type ArchiveProductReply struct{}

// ApplyDiscountRequest is the request to apply a discount to a product.
type ApplyDiscountRequest struct {
	ProductId  string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Percentage int64                  `protobuf:"varint,2,opt,name=percentage,proto3" json:"percentage,omitempty"`
	StartDate  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
}

func (r *ApplyDiscountRequest) GetProductId() string {
	if r != nil {
		return r.ProductId
	}
	return ""
}

func (r *ApplyDiscountRequest) GetPercentage() int64 {
	if r != nil {
		return r.Percentage
	}
	return 0
}

func (r *ApplyDiscountRequest) GetStartDate() *timestamppb.Timestamp {
	if r != nil {
		return r.StartDate
	}
	return nil
}

func (r *ApplyDiscountRequest) GetEndDate() *timestamppb.Timestamp {
	if r != nil {
		return r.EndDate
	}
	return nil
}

// ApplyDiscountReply is the response after applying a discount.
type ApplyDiscountReply struct{}

// RemoveDiscountRequest is the request to remove a discount from a product.
type RemoveDiscountRequest struct {
	ProductId string `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
}

func (r *RemoveDiscountRequest) GetProductId() string {
	if r != nil {
		return r.ProductId
	}
	return ""
}

// RemoveDiscountReply is the response after removing a discount.
type RemoveDiscountReply struct{}

// GetProductRequest is the request to get a product by ID.
type GetProductRequest struct {
	ProductId string `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
}

func (r *GetProductRequest) GetProductId() string {
	if r != nil {
		return r.ProductId
	}
	return ""
}

// GetProductReply is the response containing a product.
type GetProductReply struct {
	Product *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
}

func (r *GetProductReply) GetProduct() *Product {
	if r != nil {
		return r.Product
	}
	return nil
}

// ListProductsRequest is the request to list products.
type ListProductsRequest struct {
	Category   *string `protobuf:"bytes,1,opt,name=category,proto3,oneof" json:"category,omitempty"`
	Status     *string `protobuf:"bytes,2,opt,name=status,proto3,oneof" json:"status,omitempty"`
	ActiveOnly bool    `protobuf:"varint,3,opt,name=active_only,json=activeOnly,proto3" json:"active_only,omitempty"`
	Limit      int32   `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset     int32   `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (r *ListProductsRequest) GetCategory() string {
	if r != nil && r.Category != nil {
		return *r.Category
	}
	return ""
}

func (r *ListProductsRequest) GetStatus() string {
	if r != nil && r.Status != nil {
		return *r.Status
	}
	return ""
}

func (r *ListProductsRequest) GetActiveOnly() bool {
	if r != nil {
		return r.ActiveOnly
	}
	return false
}

func (r *ListProductsRequest) GetLimit() int32 {
	if r != nil {
		return r.Limit
	}
	return 0
}

func (r *ListProductsRequest) GetOffset() int32 {
	if r != nil {
		return r.Offset
	}
	return 0
}

// ListProductsReply is the response containing a list of products.
type ListProductsReply struct {
	Products   []*ProductListItem `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	TotalCount int64              `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	HasMore    bool               `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
}

func (r *ListProductsReply) GetProducts() []*ProductListItem {
	if r != nil {
		return r.Products
	}
	return nil
}

func (r *ListProductsReply) GetTotalCount() int64 {
	if r != nil {
		return r.TotalCount
	}
	return 0
}

func (r *ListProductsReply) GetHasMore() bool {
	if r != nil {
		return r.HasMore
	}
	return false
}

// Helper functions for timestamp conversion
func TimeToTimestamp(t time.Time) *timestamppb.Timestamp {
	return timestamppb.New(t)
}

func TimestampToTime(ts *timestamppb.Timestamp) time.Time {
	if ts == nil {
		return time.Time{}
	}
	return ts.AsTime()
}
